"""initial schema: repositories, indexing_jobs

Revision ID: 327309d63eb4
Revises: 
Create Date: 2026-08-14 07:24:38.512453
"""
from alembic import op
import sqlalchemy as sa


revision = '327309d63eb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('ZIP', 'GITHUB', name='sourcetype'), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('UPLOADING', 'EXTRACTING', 'SCANNING', 'SCANNED', 'PARSING', 'INDEXING', 'READY', 'FAILED', name='repostatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('total_size_bytes', sa.Integer(), nullable=False),
    sa.Column('language_breakdown', sa.JSON(), nullable=False),
    sa.Column('skipped_file_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indexing_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.Enum('EXTRACTION', 'SCANNING', 'PARSING', 'CHUNKING', 'EMBEDDING', name='jobstage'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indexing_jobs')
    op.drop_table('repositories')
    # ### end Alembic commands ###
