"""phase 4: embedding tracking columns

Revision ID: 88a6a86578b7
Revises: bfd2d3853046
Create Date: 2026-08-19 10:02:12.688748
"""
from alembic import op
import sqlalchemy as sa


revision = '88a6a86578b7'
down_revision = 'bfd2d3853046'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('chunks', sa.Column('embedding_model', sa.String(length=255), nullable=True))
    op.add_column('repositories', sa.Column('vector_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('repositories', sa.Column('embedding_provider', sa.String(length=50), nullable=True))
    op.add_column('repositories', sa.Column('embedding_model', sa.String(length=255), nullable=True))
    op.add_column('repositories', sa.Column('embedding_dimension', sa.Integer(), nullable=True))
    op.add_column('repositories', sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'indexed_at')
    op.drop_column('repositories', 'embedding_dimension')
    op.drop_column('repositories', 'embedding_model')
    op.drop_column('repositories', 'embedding_provider')
    op.drop_column('repositories', 'vector_count')
    op.drop_column('chunks', 'embedding_model')
    op.drop_column('chunks', 'embedded_at')
    # ### end Alembic commands ###
