"""phase 3: chunks, chunked files, repo chunk counters

Revision ID: bfd2d3853046
Revises: 49013cae4798
Create Date: 2026-08-16 10:13:40.945693
"""
from alembic import op
import sqlalchemy as sa


revision = 'bfd2d3853046'
down_revision = '49013cae4798'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunked_files',sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_content_hash', sa.String(length=64), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('chunked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'file_path', name='uq_chunked_files_repo_path')
    )
    op.create_table('chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('chunk_type', sa.Enum('FUNCTION', 'METHOD', 'CLASS_HEADER', 'MODULE_LEVEL', 'FUNCTION_WINDOW', 'METHOD_WINDOW', 'FILE_WINDOW', name='chunktype'), nullable=False),
    sa.Column('symbol_name', sa.String(length=255), nullable=True),
    sa.Column('parent_symbol_name', sa.String(length=255), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of_chunk_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_chunk_id'], ['chunks.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_content_hash'), 'chunks', ['content_hash'], unique=False)
    op.add_column('repositories', sa.Column('chunk_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('repositories', sa.Column('duplicate_chunk_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('repositories', sa.Column('chunked_file_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'chunked_file_count')
    op.drop_column('repositories', 'duplicate_chunk_count')
    op.drop_column('repositories', 'chunk_count')
    op.drop_index(op.f('ix_chunks_content_hash'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('chunked_files')
    # ### end Alembic commands ###
